name: App tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker backend Image
        uses: rossmaclean/docker-build-push-action@v0.0.27
        with:
          image: kauanlp/ex-simple-backend
          registry: docker.io

      - name: Build and Push Docker frontend Image
        uses: rossmaclean/docker-build-push-action@v0.0.27
        with:
          image: kauanlp/ex-simple-frontend
          registry: docker.io