name: App tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: kauanlp/ex-simple-backend:latest

      - name: Build and Push Docker frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: kauanlp/ex-simple-frontend:latest